MvcPruebExamenCripto/Models/Departamento.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace MvcPruebExamenCripto.Models
{
    [Table("DEPT")]
    public class Departamento
    {
        [Key]
        [Column("DEPT_NO")]
        public int IdDepartamento { get; set; }

        [Column("DNOMBRE")]
        public string NombreDept { get; set; }

        [Column("LOC")]
        public string Localidad { get; set; }
    }
}

MvcPruebExamenCripto/Models/Empleado.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace MMvcPruebExamenCripto.Models
{
    [Table("EMP")]
    public class Empleado
    {
        [Key]
        [Column("EMP_NO")]
        public int IdEmpleado { get; set; }

        [Column("APELLIDO")]
        public string Apellido { get; set; }

        [Column("OFICIO")]
        public string Oficio { get; set; }

        [Column("DIR")]
        public int Direccion { get; set; }

        [Column("FECHA_ALT")]
        public DateTime FechaAlta { get; set; }

        [Column("SALARIO")]
        public int Salario { get; set; }

        [Column("COMISION")]
        public int Comision { get; set; }

        [Column("DEPT_NO")]
        public int IdDepartamento { get; set; }
    }
}

MvcPruebExamenCripto/Models/ErrorViewModel.cs
namespace MvcPruebExamenCripto.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcPruebExamenCripto/Models/Usuario.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcPruebExamenCripto.Models
{
    [Table("USERS")]
    public class Usuario
    {
        [Key]
        [Column("IDUSUARIO")]
        public int IdUsario { get; set; }

        [Column("NOMBRE")]
        public string Nombre { get; set; }

        [Column("EMAIL")]
        public string Email { get; set; }

        [Column("SALT")]
        public string Salt { get; set; }

        [Column("IMAGEN")]
        public string Imagen { get; set; }
        [Column("PASS")]
        public byte[] Password { get; set; }
    }
}

MvcPruebExamenCripto/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcPruebExamenCripto.Models;
using System.Diagnostics;

namespace MvcPruebExamenCripto.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcPruebExamenCripto/Controllers/HospitalesController.cs
using Microsoft.AspNetCore.Mvc;
using MMvcPruebExamenCripto.Models;
using MvcPruebExamenCripto.Repositories;

namespace MvcPruebExamenCripto.Controllers
{
    public class HospitalesController : Controller
    {
        private RepositoryHospital repo;

        public HospitalesController(RepositoryHospital repo)
        {
            this.repo = repo;
        }

        public IActionResult Detalles(int iddepartamento)
        {
            List<Empleado> empleados = this.repo.GetEmpleados(iddepartamento);
            return View(empleados);
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

MvcPruebExamenCripto/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcPruebExamenCripto.Models;
using MvcPruebExamenCripto.Repositories;

namespace MvcPruebExamenCripto.Controllers
{
    public class UsuariosController : Controller
    {
        private RepositoryUsuarios repo;

        public UsuariosController(RepositoryUsuarios repo)
        {
            this.repo = repo;
        }
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(string nombre, string email, string password, string imagen)
        {
            await this.repo.RegisterUsuario(nombre, email, password, imagen);
            ViewData["MENSAJE"] = "Usuario registrado correctamente";
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string email,string password)
        {
            Usuario user=this.repo.LoginUser(email, password);
            if (user == null)
            {
                ViewData["MENSAJE"] = "Creacion incorrecta";
                return View();
            }
            else
            {
                HttpContext.Session.SetString("USUARIO", email);
                HttpContext.Session.SetString("PASS", password);
                return View(user);
            }
        }

        public IActionResult CerrarSesion()
        {
            HttpContext.Session.Remove("USUARIO");
            HttpContext.Session.Remove("PASS");
            return RedirectToAction("Index", "Home");
        }
    }
}

MvcPruebExamenCripto/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcPruebExamenCripto/Views/Hospitales/Detalles.cshtml
@model IEnumerable<MMvcPruebExamenCripto.Models.Empleado>

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdEmpleado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Oficio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaAlta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comision)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdDepartamento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdEmpleado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Oficio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaAlta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comision)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdDepartamento)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

MvcPruebExamenCripto/Views/Shared/Components/MenuDepartamentos/Default.cshtml
@model List<Departamento>

<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle"
            type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown"
            aria-expanded="false">
        Menú Departamentos
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        @foreach (Departamento dep in Model)
        {
                <li>
                    <a class="dropdown-item"
               asp-controller="Hospitales"
               asp-action="Detalles"
               asp-route-iddepartamento="@dep.IdDepartamento">
                    @dep.NombreDept
                    </a>
                </li>
        }
    </ul>
</div>

MvcPruebExamenCripto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcPruebExamenCripto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcPruebExamenCripto.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcPruebExamenCripto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Register">Register</a>
                        </li>
                        <partial name="_MemuUsuarios" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcPruebExamenCripto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcPruebExamenCripto/Views/Shared/_MemuUsuarios.cshtml
@{
    string usuario = Context.Session.GetString("USUARIO");
    string password = Context.Session.GetString("PASS");
}

@if (usuario == null && password==null)
{
    <li class="nav-items">
        <a asp-controller="Usuarios"
       asp-action="Login" class="nav-link">
            Log In
        </a>
    </li>
}
else
{
    <li class="nav-item">
        <a asp-controller="Usuarios" asp-action="CerrarSesion"
       class="nav-link">
            Cerrar Sesion
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Perfil</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Mis Pedidos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Comentarios</a>
    </li>
    <li class="nav-item">
        @await Component.InvokeAsync("MenuDepartamentos")
    </li>
}

MvcPruebExamenCripto/Views/Usuarios/Login.cshtml
@model Usuario

<h1>Log In User</h1>

<form method="post">
    <label>Email</label>
    <input type="text" name="email" class="form-control" />
    <label>Password</label>
    <input type="text" name="password" class="form-control" />
    <button class="btn btn-info">
        Log In
    </button>
</form>
<h1 style="color:lightskyblue">
    @ViewData["MENSAJE"]
</h1>
@if (Model != null)
{
        <h1>Bienvenido a tu apgina, @Model.Nombre</h1>
        <h1 style="color:palevioletred">Email: @Model.Email</h1>
        <img src="@Model.Imagen" style="width:150px" />
}

MvcPruebExamenCripto/Views/Usuarios/Register.cshtml
<h1>Register User</h1>

<form method="post">
    <label>Nombre</label>
    <input type="text" name="nombre" class="form-control" />
    <label>Email</label>
    <input type="text" name="email" class="form-control" />
    <label>Imagen</label>
    <input type="text" name="imagen" class="form-control" />
    <label>Password</label>
    <input type="text" name="password" class="form-control" />
    <button class="btn btn-info">
        Register
    </button>
</form>
<h1 style="color:lightskyblue">
    @ViewData["MENSAJE"]
</h1>